### PR TITLE
Sync Prettier with TSLint

### PR DESCRIPTION
**Pull request by erandagan**
Currently depends on #159, though I can probably cleanup that history if required.

### CODE REVIEW

**Comment by erandagan** [comment]
The diff here is a little scary I suppose, but that's really just the trailing comma rule being synced between prettier and TSLint :)

**Comment by Trancever** [comment]
@erandagan Please fix lint CI check. Let's make CI green again :)

**Comment by erandagan** [comment]
> @erandagan Please fix lint CI check. Let's make CI green again :)
Will do 👌

**Comment by erandagan** [comment]
CI is back to green - merging.

**Pull request merged**
