### PR TITLE
Migrate to Typescript

### LINKED ISSUE #128: [Discussion] Consider TS Migration
Main arguments from the Expo team
https://github.com/expo/expo/issues/2164

I'm aware callstack generally use Flow for their typings, but it feels like TS would make it easier for contributors (including myself) to jump in.

We have very few JS files so migrating should be easy.

Thoughts?
@Suraj-Tiwari @Trancever

### PR DESCRIPTION
**Pull request by erandagan**
Resolves #128 
I'll setup Circle CI + TS in a separate PR.

Existing code should continue working as-is since all top level imports, props and such were unaffected.

### CODE REVIEW

**Comment by erandagan** [comment]
Don't merge this yet as there are a few TS errors left in withNativeAd. I won't be available for this until Friday

**Comment by Suraj-Tiwari** [comment]
Ok no problem I'll have a look at it too this weekend.

**Comment by erandagan** [comment]
I did check this, works fine on both iOS and Android.

**Comment by Suraj-Tiwari** [comment]
Tested with Media removed from ad placement.?  just like a banner ad?

**Comment by erandagan** [comment]
@Suraj-Tiwari I've tested with an ad that uses AdIconView, AdChoicesView and others, not the Media component. There is no difference in the AdIcon and Media implementation so it should work, but if you could give this a shot as well it would be great :)

**Comment by erandagan** [comment]
The last of the typescript errors has been resolved, will move on to testing this today and prepare for merge.

**Comment by erandagan** [comment]
@Trancever @Suraj-Tiwari 
This PR is ready for review, I'd appreciate you could have a look so we can proceed to merge it and releasing a version with all the recent changes.

**Comment by Trancever** [comment]
@erandagan Do we really need to add gradle-wrapper.jar and gradle-wrapper.properties files to git?

**Comment by erandagan** [comment]
> @erandagan Do we really need to add gradle-wrapper.jar and gradle-wrapper.properties files to git?
Well maybe it's a bit out of the scope of this PR, but generally this is the good practice in Android development as multiple users may have multiple versions of Gradle. The Gradle Wrapper associates a gradle version with the project, ensures it's installed, and routes any gradle invocations to that particular instance. So yeah, perhaps a bit out of scope here, but not too big of a deal and generally it's for the best :)

**Comment by Trancever** [comment]
@erandagan Sorry for 3 comments. It was caused by github outage probably..

**Pull request merged**
