### PR TITLE
Adding podspec to the project and changes to documentation in README.md

### PR DESCRIPTION
**Pull request by abhaynpai**
Adding podspec to build project for RN >= 0.60

Fixing issue for #92 and #212 

@Suraj-Tiwari @erandagan Kindly review

### CODE REVIEW

**Comment by Trancever** [comment]
@Suraj-Tiwari Can you check this and merge? We need to publish new version with this.

**Comment by khuyendev** [comment]
please merge,

**Comment by Suraj-Tiwari** [comment]
@abhaynpai can you please stash the commits for a fast review?

**Comment by abhaynpai** [comment]
@Suraj-Tiwari : Can you kindly share the steps that needs to be taken to stash the commit?

**Comment by abhaynpai** [comment]
I tried squashing the commits and looks like something has gone wrong here. 

I have a backup of the files. I can fork the repo again, update the files and create a new PR if required.

@Suraj-Tiwari : Let me know the steps that needs to be taken here.

**Comment by Suraj-Tiwari** [comment]
Send a new pr with stashed commit, that will be easy and fast.

**Comment by abhaynpai** [comment]
@Suraj-Tiwari : Sure. I'll do that in a bit.

**Comment by abhaynpai** [comment]
Closing this PR and creating a new one.

**Comment by abhaynpai** [comment]
@Suraj-Tiwari : I have created the new PR #216 . Kindly review.

**Pull request closed without merging**
