### PR TITLE
Adding podspec file to support RN >= 0.60

### PR DESCRIPTION
**Pull request by abhaynpai**
@Suraj-Tiwari : Kindly review.

### CODE REVIEW

**Comment by tmjordan** [comment]
@abhaynpai i tried to use your fork but id does not work. I have an error with metro bundler

**Comment by Suraj-Tiwari** [comment]
@tmjordan did you tried cleaning cache?? 
`react-native start --resetCache` ?

**Comment by tmjordan** [comment]
yes i did, but still not working

**Comment by Suraj-Tiwari** [comment]
@abhaynpai can you please check this fix in a new project? 
@tmjordan what's your react-native version ? or can you test this in a new project?

**Comment by tmjordan** [comment]
@Suraj-Tiwari react-native 0.60.5
ok i will try

**Comment by tmjordan** [comment]
@Suraj-Tiwari still not working for me

**Comment by abhaynpai** [comment]
I'll test it on a new project by the end of today and make changes if required.

**Comment by abhaynpai** [comment]
@tmjordan : Can you share the issue that you are facing with the metro bundler?

**Comment by abhaynpai** [comment]
@tmjordan : I tried running the changes in the PR and it's working fine. I guess you need to run `npm run tsc` inside your project's `node_modules/react-native-fbads` to fix the issue. You might see some errors while running the command, ignore them and re-run your project.

Try running the above command and let me know if it worked for you or not. If not then share the stacktrace and details of the issue that you are facing.

**Comment by tmjordan** [comment]
@abhaynpai Here is the error i get:
`error: bundling failed: Error: While trying to resolve module `react-native-fbads` from file `C:\Users\nount\WebstormProjects\daate2\src\screens\user\showProfile4.js`, the package `C:\Users\nount\WebstormProjects\daate2\node_modules\react-native-fbads\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\nount\WebstormProjects\daate2\node_modules\react-native-fbads\dist\lib\index.js`. Indeed, none of these files exist:
`

**Comment by tmjordan** [comment]
@abhaynpai i finally make it work. I didn't know that i needed to install typescript.
I installed then i execute the command you said, then it worked.
Thank you very much :)

**Comment by abhaynpai** [comment]
@tmjordan : No worries 👍 

@Suraj-Tiwari : Kindly review and merge the PR.

**Comment by Suraj-Tiwari** [comment]
Cool, I'll merge it tonight.

**Comment by Suraj-Tiwari** [comment]
@Trancever please make a release,

**Comment by Trancever** [comment]
Version 6.2.0 released. Let us know if it works for you!

**Comment by tmjordan** [comment]
@Trancever @Suraj-Tiwari  I tried to install the last version, but i have an error on iOS, everything is good on android.
image

**Comment by tmjordan** [comment]
@abhaynpai Is it normal, that i need to execute `npm run tsc` to make it work ?

**Comment by abhaynpai** [comment]
@Suraj-Tiwari @Trancever :

The `ReactNativeAdsFacebook.podspec` file needs to be added in the `package.json` under the `files` array. I think the file is missing while publishing the package to NPM.

https://github.com/callstack/react-native-fbads/blob/4690841fabf1cee86b7f7d72d7fec7a4067373d4/package.json#L46

**Comment by Trancever** [comment]
@abhaynpai Check 6.2.1 version

**Comment by abhaynpai** [comment]
@Trancever : Awesome. I just checked the commit. I'll cross check with the package in sometime. Thanks.

**Pull request merged**
