### PR TITLE
same FRAMEWORK_SEARCH_PATHS & HEADER_SEARCH_PATHS as fb sdk

### PR DESCRIPTION
**Pull request by philipheinser**
This is needed if you like to keep the fb frameworks in your project and not in the user directory.

#25

### CODE REVIEW

**Comment by grabbou** [comment]
Where this path `"${SRCROOT}/../../../../ios/**",` is supposed to point to? When using FBAds with CococaPods, I guess Headers are populated anyways.

Could you write location where your FBAds SDK is installed?

**Comment by philipheinser** [comment]
@grabbou I only wanted to ad this `FRAMEWORK_SEARCH_PATHS = (
 					"~/Documents/FacebookSDK",
 					"$(PROJECT_DIR)/../../../../ios/Frameworks",
 				);`

**Comment by grabbou** [comment]
I know, but I don't recognise this location and so, would like to understand what's the directory structure before merging.

If I understand correctly, you are having `<root>/ios/Frameworks` folder with FacebookSDK located in there, right? Is there any standard pattern on `iOS` for keeping these, just like on Android there's `libs` folder?

**Comment by philipheinser** [comment]
@grabbou So `<root>/ios/` is standard path for iOS Project in react native. `Frameworks ` is the standard folder for frameworks in iOS. Yes just like `libs` in android.

**Comment by grabbou** [comment]
Makes sense!

**Pull request closed without merging**
