### PR TITLE
Add preload functionality to Interstitial Ads

### PR DESCRIPTION
**Pull request by Jhonte**
### Summary

Today the Interstitial loads and then shows up.  But in time critical scenarios it is better for the UX if the ad already is ready and loaded once it should be shown.

### CODE REVIEW

**Comment by Jhonte** [comment]
Also includes this revert, https://github.com/callstack/react-native-fbads/pull/237/commits/1b3d7f761a1e646f5c42ea1323158ae8763196e5
Since the banner did not show all content and therefore not clickable.

**Comment by ngocsang103** [comment]
Hi Johan Andersson!
 I test  only for android but i get error. I use the same code in https://github.com/callstack/react-native-fbads/blob/1b3d7f761a1e646f5c42ea1323158ae8763196e5/android/app/src/main/java/suraj/tiwari/reactnativefbads/InterstitialAdManager.java
and then use the file https://github.com/callstack/react-native-fbads/blob/c5610045d0cf28546afb08890f96744335ad1f50/src/InterstitialAdManager.ts in the react native 
error : 
TypeError: _reactNativeFbads.InterstitialAdManager.preloadAd is not a function. (In '_reactNativeFbads.InterstitialAdManager.preloadAd(_adsId.interPlaceId)', '_reactNativeFbads.InterstitialAdManager.preloadAd' is undefined)

please help me.

**Comment by Jhonte** [comment]
> Hi Johan Andersson!
> I test only for android but i get error. I use the same code in https://github.com/callstack/react-native-fbads/blob/1b3d7f761a1e646f5c42ea1323158ae8763196e5/android/app/src/main/java/suraj/tiwari/reactnativefbads/InterstitialAdManager.java
> and then use the file https://github.com/callstack/react-native-fbads/blob/c5610045d0cf28546afb08890f96744335ad1f50/src/InterstitialAdManager.ts in the react native
> When i run i get the error :
> TypeError: _reactNativeFbads.InterstitialAdManager.preloadAd is not a function. (In '_reactNativeFbads.InterstitialAdManager.preloadAd(_adsId.interPlaceId)', '_reactNativeFbads.InterstitialAdManager.preloadAd' is undefined)
> 
> please help me.

That isn't due to this PR though.

**Comment by Suraj-Tiwari** [comment]
@Jhonte thanks

**Pull request merged**
