### PR TITLE
AdChoicesView Props Overhaul

### PR DESCRIPTION
**Pull request by erandagan**
This PR continues the discussion in https://github.com/callstack/react-native-fbads/issues/122.

- Removed AdChoices positionStyle in favour of a fully customisable style. Default style remains top left corner.
- Renamed props passed to `withNativeAd` to better reflect their effect:
  - `adChoicePosition` prop renamed to `adChoiceStyle`
  - `expandable` prop renamed to `adChoiceExpandable`

Note that this PR introduces the following **breaking changes**:
- `adChoicePosition` has been removed. Use `adChoiceStyle` instead.
- `expandable`  has been renamed to `adChoiceExpandable`

I think that in order to get this package to a more stable & customisable state, we'll have to introduce some breaking changes to improve the API.

### CODE REVIEW

**Comment by erandagan** [comment]
@Trancever @Suraj-Tiwari I still believe that it's better if we let the user include AdChoices wherever he likes, rather than enabling just the styling props.

True, removing the default AdChoices will introduce a breaking change, but I think that long term it's better as the major selling point of Native Ads is full control over the Ad's appearance, and the current usage of AdChoices isn't quite there.

**Comment by Trancever** [comment]
@erandagan I don't have much time during weekend, will check it on Monday.

**Comment by Suraj-Tiwari** [comment]
@erandagan I think we should go with a fixed plan rather than having multiple changes over the time.

Either we make it a separate component or take it with stylesheet.
Please follow this plan or suggest better plan of you have: 

Plan A: 
- [ ] Adchoice Separate component.
This will give full control.

To do this remove it from [here](https://github.com/callstack/react-native-fbads/blob/f4cc9a809ddfcfe6ec9221fdf423f51366e6a112/withNativeAd.js#L188).

Required prop `placement_id` is already passed from [here](https://github.com/callstack/react-native-fbads/blob/f4cc9a809ddfcfe6ec9221fdf423f51366e6a112/withNativeAd.js#L210) 

rest of it will be same and users can implement it like this `import {AdChoicesView} from 'react-native-fbads'`

Plan B: 
- [ ] `this.props.position || this.props.style` 

This is because if someone don't want fancy stylesheet he/she can go with just position props to save time. Not everyone use Advanced feature


### If decided to have a separate component submit a new pr. 

I'm going outstation for a week from today so, I won't have my laptop with me but I'll have access to my gmail and discord channel for any discussion you can reach me there.

**Comment by erandagan** [comment]
@Suraj-Tiwari Sounds good!
I think that we'll go with Plan A, as we expect users to be familiar with styling in RN (which is rather simple)

I'll go ahead and close this PR and open a separate one for the component.

**Pull request closed without merging**
