### PR TITLE
chore: adds circleCi config + fix eslint, flow errors.

### PR DESCRIPTION
**Pull request by Trancever**
This PR adds running eslint on CI. A lot of code has been changed according to callstack's eslint config and react-native plugin. Once typescript definitions are ready, we will also add checking them on CI.

### CODE REVIEW

**Comment by erandagan** [comment]
It seems like there are conflicting settings between prettier and the ESLint formatter, namely tailing commas in objects. Maybe add https://github.com/prettier/eslint-config-prettier to the ESLint config?

**Comment by Trancever** [comment]
Good catch. Set `trailingComma` to `es5` in `.prettierrc`.

**Comment by erandagan** [comment]
Cool. I think there may be a few more conflicts in regards to line lengths, single line lambdas and such. Could you please try running ESLint and then Prettier and ensure nothing changes?

I'm just away from my dev env right now so I can't test this myself :)

**Comment by Trancever** [comment]
Everything is set up properly right now. I run prettier on all files.

**Pull request merged**
