### PR TITLE
fixes rc package version to be semver compliant

### PR DESCRIPTION
**Pull request by Jobeso**
This commit changes the rc package version to be compliant with semver convention. Now it is possible to successfully add the master branch with yarn.

### CODE REVIEW

**Comment by erandagan** [comment]
Thank you for submitting this PR! This is a small yet important detail.

The package should now be at 6.0.0.rc.3, as we already released the first RC for 6.0.0 and the second RC was mistakenly released under 6.0.2. If you could change that it would be great 👍 

Other than that looks good.

CC @Trancever :)

**Comment by Jobeso** [comment]
Hey @erandagan,
changed the version accordingly :)

**Comment by erandagan** [comment]
Good job, thanks for submitting! 
@Trancever Can we get this on NPM?

**Comment by Trancever** [comment]
@erandagan I'll publish it tommorow.

**Pull request merged**
